language: php

php:
  - 5.6
  - 7.0

services:
    - mysql

before_script:
    -mysql -e 'create database orm;'

before_install:
    -mysql -u root -e "CREATE DATABASE IF NOT EXISTS orm;"

script:
    - mkdir -p build/logs
    - composer install
    - phpunit --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry  php vendor/bin/coveralls
    - travis_retry php vendor/bin/coveralls -v